name: release
on: 
  push: {}
  workflow_dispatch:
    inputs:
        environment:
          type: choice
          description: Choose environment
          options: 
          - qa1
          - uat
          - prod
  
env:
  AWS_REGION: us-east-1
  ENV: ${{ github.event.inputs.environment }} || 'qa1'
jobs:
  release:
    runs-on: ubuntu-latest
    # permissions for AWS Action to interact with GitHub's OIDC endpoint
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Echo out environment
        run: echo ${{ env.ENV }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - name: Install dependencies
        run: yarn install --check-files
      - name: cdk synth
        run: npx cdk synth
      - name: cdk bootstrap
        run: npx cdk bootstrap  
      - name: cdk deploy
        run: npx cdk deploy --require-approval never